/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Compute MinHash signature for a text string.
 * Uses character 3-grams (shingles) and 128 FNV-1a hash functions.
 * Returns a 128-element signature array.
 */
export declare function computeMinhash(text: string, numHashes: number, shingleSize: number): Array<number>
/** Compute MinHash signatures for a batch of texts in parallel. */
export declare function batchComputeMinhash(texts: Array<string>, numHashes: number, shingleSize: number): Array<Array<number>>
/** Estimate Jaccard similarity from two MinHash signatures. */
export declare function minhashJaccard(sigA: Array<number>, sigB: Array<number>): number
/**
 * Batch compare one signature against many candidates in parallel.
 * Returns Jaccard similarity for each candidate.
 */
export declare function batchMinhashJaccard(querySig: Array<number>, candidateSigs: Array<Array<number>>): Array<number>
export interface DedupCandidate {
  id: string
  embeddingSimilarity: number
  minhashSimilarity: number
  titleSimilarity: number
  repositoryOverlap: boolean
}
export interface DedupWeights {
  embedding: number
  minhash: number
  title: number
  repository: number
}
export interface DedupResult {
  id: string
  combinedScore: number
}
/**
 * Score dedup candidates using weighted multi-signal formula.
 * Runs in parallel across all candidates.
 */
export declare function scoreDedupCandidates(candidates: Array<DedupCandidate>, weights: DedupWeights, mergeThreshold: number): Array<DedupResult>
/**
 * Compute Jaccard similarity between two tokenized texts.
 * Tokenizes by splitting on whitespace and punctuation, lowercasing,
 * filtering tokens < 3 chars.
 */
export declare function titleJaccardSimilarity(textA: string, textB: string): number
/** Batch title similarity — compare one title against many in parallel. */
export declare function batchTitleSimilarity(queryTitle: string, candidateTitles: Array<string>): Array<number>
/**
 * Validate that all values in an embedding vector are finite.
 * Returns true if valid, false if any NaN/Inf detected.
 */
export declare function validateEmbedding(embedding: Array<number>, expectedDimensions: number): boolean
/**
 * Batch validate embeddings in parallel.
 * Returns indices of invalid embeddings (empty = all valid).
 */
export declare function batchValidateEmbeddings(embeddings: Array<Array<number>>, expectedDimensions: number): Array<number>
/**
 * Generate deterministic pseudo-embeddings for development/testing.
 * Produces normalized vectors from text content (not semantically meaningful).
 * Runs in parallel across all texts.
 */
export declare function generateLocalEmbeddings(texts: Array<string>, dimensions: number): Array<Array<number>>
/**
 * Compute FNV-1a fingerprint of a text string.
 * Used for bloom filter registration and fast dedup pre-checks.
 */
export declare function fnv1AFingerprint(text: string): number
/** Batch fingerprint computation in parallel. */
export declare function batchFnv1AFingerprint(texts: Array<string>): Array<number>
export interface CandidateScores {
  semantic: number
  keyword: number
  entityMatch: number
  temporal: number
  graphRelevance: number
}
export interface CandidateInput {
  id: string
  sessionId?: string
  contentLength: number
  tokenCount: number
  qualityScore: number
  usageCount: number
  upvotes: number
  createdAtMs: number
  lastAccessedAtMs?: number
  confidence: string
  repository?: string
  scores: CandidateScores
  source: string
}
export interface RankingWeights {
  semantic: number
  keyword: number
  freshness: number
  repoMatch: number
  authorReputation: number
  usage: number
  upvotes: number
  quality: number
  graph: number
}
export interface RankingContext {
  queryRepository?: string
  nowMs: number
}
export interface ScoredCandidate {
  id: string
  finalScore: number
  semanticContribution: number
  keywordContribution: number
  freshnessContribution: number
  repoMatchContribution: number
  usageContribution: number
  qualityContribution: number
  graphContribution: number
  diversityPenalty: number
}
/**
 * Reciprocal Rank Fusion — merge multiple ranked lists into one.
 * Each list contributes 1/(k + rank) for each item. Items appearing
 * in multiple lists accumulate more evidence.
 *
 * Runs in parallel across the input lists using Rayon.
 */
export declare function rrfFuse(rankedLists: Array<Array<string>>, k: number): Array<string>
/**
 * Score and rank all candidates using the composite formula.
 * Runs the scoring in parallel across all candidates.
 *
 * Returns candidates sorted by final_score descending.
 */
export declare function rankCandidates(candidates: Array<CandidateInput>, weights: RankingWeights, context: RankingContext): Array<ScoredCandidate>
/**
 * Greedy token-budget packing: iterate over ranked candidates and include
 * each one until the cumulative token count reaches the budget.
 * Always returns at least one result.
 */
export declare function packByTokenBudget(rankedIds: Array<string>, tokenCounts: Array<number>, maxTokens: number): Array<string>
/**
 * Compute temporal scores for a batch of items in parallel.
 * Uses exponential decay with configurable half-life.
 */
export declare function computeTemporalScores(createdAtMsList: Array<number>, lastAccessedMsList: Array<number | undefined | null>, confidenceList: Array<string>, nowMs: number, halfLifeDays: number): Array<number>
/**
 * Compute cosine similarity between a query vector and multiple candidate vectors.
 * Runs in parallel across candidates. Used for dedup threshold checks.
 */
export declare function batchCosineSimilarity(queryVec: Array<number>, candidateVecs: Array<Array<number>>): Array<number>
/**
 * Compute Jaccard overlap between query entities and each candidate's entities.
 * Runs in parallel.
 */
export declare function batchEntityOverlap(queryEntities: Array<string>, candidateEntities: Array<Array<string>>): Array<number>
