/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CandidateScores {
  semantic: number
  keyword: number
  entityMatch: number
  temporal: number
  graphRelevance: number
}
export interface CandidateInput {
  id: string
  sessionId?: string
  contentLength: number
  tokenCount: number
  qualityScore: number
  usageCount: number
  upvotes: number
  createdAtMs: number
  lastAccessedAtMs?: number
  confidence: string
  repository?: string
  scores: CandidateScores
  source: string
}
export interface RankingWeights {
  semantic: number
  keyword: number
  freshness: number
  repoMatch: number
  authorReputation: number
  usage: number
  upvotes: number
  quality: number
  graph: number
}
export interface RankingContext {
  queryRepository?: string
  nowMs: number
}
export interface ScoredCandidate {
  id: string
  finalScore: number
  semanticContribution: number
  keywordContribution: number
  freshnessContribution: number
  repoMatchContribution: number
  usageContribution: number
  qualityContribution: number
  graphContribution: number
  diversityPenalty: number
}
/**
 * Reciprocal Rank Fusion — merge multiple ranked lists into one.
 * Each list contributes 1/(k + rank) for each item. Items appearing
 * in multiple lists accumulate more evidence.
 *
 * Runs in parallel across the input lists using Rayon.
 */
export declare function rrfFuse(rankedLists: Array<Array<string>>, k: number): Array<string>
/**
 * Score and rank all candidates using the composite formula.
 * Runs the scoring in parallel across all candidates.
 *
 * Returns candidates sorted by final_score descending.
 */
export declare function rankCandidates(candidates: Array<CandidateInput>, weights: RankingWeights, context: RankingContext): Array<ScoredCandidate>
/**
 * Greedy token-budget packing: iterate over ranked candidates and include
 * each one until the cumulative token count reaches the budget.
 * Always returns at least one result.
 */
export declare function packByTokenBudget(rankedIds: Array<string>, tokenCounts: Array<number>, maxTokens: number): Array<string>
/**
 * Compute temporal scores for a batch of items in parallel.
 * Uses exponential decay with configurable half-life.
 */
export declare function computeTemporalScores(createdAtMsList: Array<number>, lastAccessedMsList: Array<number | undefined | null>, confidenceList: Array<string>, nowMs: number, halfLifeDays: number): Array<number>
/**
 * Compute cosine similarity between a query vector and multiple candidate vectors.
 * Runs in parallel across candidates. Used for dedup threshold checks.
 */
export declare function batchCosineSimilarity(queryVec: Array<number>, candidateVecs: Array<Array<number>>): Array<number>
/**
 * Compute Jaccard overlap between query entities and each candidate's entities.
 * Runs in parallel.
 */
export declare function batchEntityOverlap(queryEntities: Array<string>, candidateEntities: Array<Array<string>>): Array<number>
