{{- if .Values.availability.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: {{ .Release.Name }}-api }
spec:
  minAvailable: {{ .Values.availability.podDisruptionBudget.apiMinAvailable }}
  selector:
    matchLabels: { app.kubernetes.io/name: synapse, app.kubernetes.io/component: api }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: {{ .Release.Name }}-worker }
spec:
  minAvailable: {{ .Values.availability.podDisruptionBudget.workerMinAvailable }}
  selector:
    matchLabels: { app.kubernetes.io/name: synapse, app.kubernetes.io/component: worker }
{{- end }}
