{{- if eq .Values.secrets.provider "env" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-credentials
type: Opaque
stringData:
  url: "postgresql://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@{{ include "db.host" . }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-credentials
type: Opaque
stringData:
  url: "redis://{{ if .Values.redis.password }}:{{ .Values.redis.password }}@{{ end }}{{ include "redis.host" . }}:{{ .Values.redis.port }}"
---
{{- if .Values.objectStorage.accessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3-credentials
type: Opaque
stringData:
  accessKey: "{{ .Values.objectStorage.accessKey }}"
  secretKey: "{{ .Values.objectStorage.secretKey }}"
{{- end }}
{{- end }}
