/**
 * Observation Generator (v3 — Mental Models)
 *
 * Generates and refreshes entity observations (pre-computed entity summaries).
 * Inspired by Hindsight's "Observation Network" — synthesized, preference-neutral
 * profiles of entities derived from underlying facts.
 *
 * Observations serve as a fast-retrieval cache: instead of loading 20 facts about
 * "Kafka" and synthesizing every query, we maintain a pre-computed summary that
 * gets refreshed when new facts arrive.
 *
 * Triggers:
 *   1. After fact extraction: if new facts mention an entity with 3+ total facts,
 *      schedule observation refresh.
 *   2. During compaction: refresh stale observations (>7 days old with new facts).
 *   3. On-demand via reflect: if a query focuses on an entity and its observation
 *      is missing or stale, generate inline.
 *
 * Design:
 *   - Observations are objective (no opinion/persona), factual summaries
 *   - Generated by LLM when available, or by concatenation fallback
 *   - Max ~100 tokens each (concise entity profiles)
 *   - Stored with embedding for semantic retrieval
 *   - Updated (not versioned) — only the latest observation is kept
 */

import { v4 as uuidv4 } from 'uuid';
import { Worker, Job } from 'bullmq';
import { createChildLogger } from '../utils/logger.js';
import { getConfig } from '../config/index.js';
import { LlmClient } from '../utils/llm.js';
import { EmbeddingClient } from '../utils/embedding.js';
import { FactRepository } from '../storage/fact-repository.js';
import { ObservationRepository } from '../storage/observation-repository.js';
import { type MemoryFact } from '../models/index.js';
import { type Observation } from '../models/reflect.js';

const logger = createChildLogger({ module: 'observation-generator' });

// ─── Configuration ───────────────────────────────────────────────────────────

export interface ObservationGeneratorConfig {
  /** Minimum facts needed before generating an observation */
  minFactCount: number;
  /** Maximum age (hours) before an observation is considered stale */
  maxAgeHours: number;
  /** Maximum observations to generate/refresh per run */
  maxPerRun: number;
}

const DEFAULT_CONFIG: ObservationGeneratorConfig = {
  minFactCount: 3,
  maxAgeHours: 168, // 7 days
  maxPerRun: 100,
};

// ─── Prompt ──────────────────────────────────────────────────────────────────

const OBSERVATION_PROMPT = `You are a technical entity summarizer for a software engineering knowledge base. Given facts about a specific entity (technology, service, concept, person), produce a concise, objective observation.

Rules:
- Be factual and objective — no opinions or speculation
- Include: what it is, how it's used in the organization, key constraints, relevant decisions
- Keep it under 100 tokens — this is a quick reference, not an article
- Write in third person
- If facts contradict, prefer the most recent one
- Include the most actionable/useful information first

Output a single paragraph — the observation text only, no formatting or labels.`;

// ─── Queue ───────────────────────────────────────────────────────────────────

export const OBSERVATION_QUEUE_NAME = 'observation-generation';

export interface ObservationJob {
  entityName: string;
  organizationId: string;
  triggerFactId?: string; // The fact that triggered this refresh
}

// ─── Generator ───────────────────────────────────────────────────────────────

export class ObservationGenerator {
  private config: ObservationGeneratorConfig;
  private llm: LlmClient;
  private embeddingClient: EmbeddingClient;
  private factRepo: FactRepository;
  private observationRepo: ObservationRepository;

  constructor(config: Partial<ObservationGeneratorConfig> = {}) {
    this.config = { ...DEFAULT_CONFIG, ...config };
    this.llm = new LlmClient();
    this.embeddingClient = new EmbeddingClient();
    this.factRepo = new FactRepository();
    this.observationRepo = new ObservationRepository();
  }

  /**
   * Generate or refresh an observation for a specific entity.
   * Returns the observation if generated/updated, null if skipped.
   */
  async generateForEntity(
    entityName: string,
    organizationId: string,
  ): Promise<Observation | null> {
    // Load all current facts about this entity
    const facts = await this.factRepo.findByEntities(
      [entityName],
      organizationId,
      { limit: 30, onlyValid: true },
    );

    if (facts.length < this.config.minFactCount) {
      logger.debug({ entityName, factCount: facts.length }, 'Not enough facts for observation');
      return null;
    }

    // Check if existing observation is still fresh
    const existing = await this.observationRepo.findByEntity(entityName, organizationId);
    if (existing) {
      const ageHours = (Date.now() - new Date(existing.updatedAt).getTime()) / 3600000;
      if (ageHours < this.config.maxAgeHours && existing.sourceFactCount >= facts.length) {
        logger.debug({ entityName, ageHours }, 'Observation still fresh, skipping');
        return existing;
      }
    }

    // Generate the observation
    const summary = await this.synthesize(entityName, facts);
    if (!summary) return existing ?? null;

    // Generate embedding for the observation
    const embeddingText = `${entityName}: ${summary}`;
    const embedding = await this.embeddingClient.embed(embeddingText);

    const observation: Observation = {
      id: existing?.id ?? uuidv4(),
      entityName,
      organizationId,
      summary,
      sourceFactIds: facts.map(f => f.id),
      sourceFactCount: facts.length,
      embedding,
      createdAt: existing?.createdAt ?? new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    await this.observationRepo.upsert(observation);

    logger.info({
      entityName,
      factCount: facts.length,
      isNew: !existing,
      summaryLength: summary.length,
    }, 'Observation generated');

    return observation;
  }

  /**
   * Refresh all stale observations for an organization.
   * Intended to be called from compaction or a scheduled job.
   */
  async refreshStale(organizationId: string): Promise<{
    refreshed: number;
    skipped: number;
    errors: number;
  }> {
    const stale = await this.observationRepo.findStale(
      organizationId,
      this.config.maxPerRun,
    );

    let refreshed = 0;
    let skipped = 0;
    let errors = 0;

    for (const observation of stale) {
      try {
        const result = await this.generateForEntity(
          observation.entityName,
          organizationId,
        );
        if (result && result.updatedAt !== observation.updatedAt) {
          refreshed++;
        } else {
          skipped++;
        }
      } catch (error) {
        errors++;
        logger.warn({
          err: error,
          entityName: observation.entityName,
        }, 'Failed to refresh observation');
      }
    }

    logger.info({ organizationId, refreshed, skipped, errors }, 'Stale observation refresh complete');
    return { refreshed, skipped, errors };
  }

  /**
   * Discover entities that have enough facts but no observation yet.
   * Generates observations for the top entities by fact count.
   */
  async discoverAndGenerate(organizationId: string): Promise<number> {
    // Find entities with 3+ facts that have no observation
    const entitiesWithCounts = await this.findEntitiesWithoutObservations(organizationId);
    let generated = 0;

    for (const { entityName } of entitiesWithCounts.slice(0, this.config.maxPerRun)) {
      try {
        const result = await this.generateForEntity(entityName, organizationId);
        if (result) generated++;
      } catch (error) {
        logger.warn({ err: error, entityName }, 'Failed to generate observation');
      }
    }

    logger.info({ organizationId, discovered: entitiesWithCounts.length, generated }, 'Discovery complete');
    return generated;
  }

  // ─── Internal ──────────────────────────────────────────────────────────────

  /**
   * Synthesize an observation summary from facts.
   * Uses LLM when available, concatenation fallback otherwise.
   */
  private async synthesize(entityName: string, facts: MemoryFact[]): Promise<string | null> {
    const factsText = facts
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
      .map(f => {
        const age = f.temporal.validUntil ? '(superseded)' : '(current)';
        return `- [${f.type}] ${f.content} ${age}`;
      })
      .join('\n');

    if (!this.llm.disabled) {
      const userPrompt = `Entity: "${entityName}"\n\nFacts (${facts.length} total, most recent first):\n${factsText}`;
      const response = await this.llm.generate(OBSERVATION_PROMPT, userPrompt);
      if (response) {
        return response.text.trim();
      }
    }

    // Fallback: concatenate the top 3 most recent current facts
    const currentFacts = facts
      .filter(f => !f.temporal.validUntil)
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
      .slice(0, 3);

    if (currentFacts.length === 0) return null;

    return `${entityName}: ${currentFacts.map(f => f.content).join('. ')}.`;
  }

  /**
   * Find entities that have sufficient facts but no observation yet.
   */
  private async findEntitiesWithoutObservations(
    organizationId: string,
  ): Promise<Array<{ entityName: string; factCount: number }>> {
    // Query facts grouped by entity, excluding those with existing observations
    const { query: dbQuery } = await import('../storage/database.js');
    const result = await dbQuery<{
      [column: string]: unknown;
      entity_name: string;
      fact_count: string;
    }>(`
      WITH entity_facts AS (
        SELECT unnest(entities) AS entity_name, COUNT(*) AS fact_count
        FROM memory_facts
        WHERE organization_id = $1
          AND (temporal_valid_until IS NULL OR temporal_valid_until > NOW())
        GROUP BY unnest(entities)
        HAVING COUNT(*) >= $2
      )
      SELECT ef.entity_name, ef.fact_count::text
      FROM entity_facts ef
      LEFT JOIN observations o
        ON o.organization_id = $1 AND LOWER(o.entity_name) = LOWER(ef.entity_name)
      WHERE o.id IS NULL
      ORDER BY ef.fact_count DESC
      LIMIT $3
    `, [organizationId, this.config.minFactCount, this.config.maxPerRun]);

    return result.rows.map(row => ({
      entityName: row.entity_name,
      factCount: parseInt(row.fact_count, 10),
    }));
  }
}

// ─── Worker Setup ────────────────────────────────────────────────────────────

let observationWorker: Worker | null = null;

export function startObservationWorker(): Worker {
  if (observationWorker) return observationWorker;

  const config = getConfig();
  const generator = new ObservationGenerator();

  observationWorker = new Worker(
    OBSERVATION_QUEUE_NAME,
    async (job: Job<ObservationJob>) => {
      const { entityName, organizationId, triggerFactId } = job.data;
      logger.info({ entityName, organizationId, triggerFactId }, 'Processing observation job');

      const observation = await generator.generateForEntity(entityName, organizationId);
      return {
        entityName,
        generated: !!observation,
        summary: observation?.summary?.substring(0, 80),
      };
    },
    {
      connection: { url: config.REDIS_URL },
      concurrency: 4,
      limiter: { max: 20, duration: 60000 }, // Max 20/min to control LLM costs
    },
  );

  observationWorker.on('failed', (job, err) => {
    logger.error({ entityName: job?.data.entityName, err }, 'Observation job failed');
  });

  logger.info('Observation generation worker started');
  return observationWorker;
}

export async function stopObservationWorker(): Promise<void> {
  if (observationWorker) { await observationWorker.close(); observationWorker = null; }
}
